import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../components/ui/Button';
import { 
  Car, 
  UserPlus, 
  FileText, 
  UploadCloud, 
  Clock, 
  ShieldCheck, 
  CreditCard, 
  Sparkles, 
  Check, 
  UserCheck, 
  Shield, 
  TrendingUp, 
  HelpCircle, 
  PhoneCall, 
  CheckCircle,
  ChevronDown,
  ChevronUp,
  ArrowRight
} from 'lucide-react';
import { useSEO } from '../hooks/useSEO';

export function HowItWorks() {
  useSEO({
    title: 'How It Works | No Credit Barrier Rent-to-Buy Steps | R2BuyCar',
    description: 'Understand the clear, step-by-step pathway from flexible car renting to full vehicle ownership. No strict bank score thresholds, no application feed burdens, plus complete road servicing covered.',
    keywords: 'how rent to buy works, hire purchase car, bad credit car lease UK, buycarz roadmap, R2BuyCar guide'
  });

  const [openFaqIdx, setOpenFaqIdx] = useState(null);

  const steps = [
    {
      num: '1',
      title: 'Browse Available Cars',
      desc: 'Choose from our range of quality vehicles and find the one that suits your needs.',
      icon: Car,
      accent: 'indigo'
    },
    {
      num: '2',
      title: 'Create Your Account',
      desc: 'Register and complete your profile to begin your application.',
      icon: UserPlus,
      accent: 'indigo'
    },
    {
      num: '3',
      title: 'Submit Application',
      desc: 'Fill out the application form and provide the required information.',
      icon: FileText,
      accent: 'indigo'
    },
    {
      num: '4',
      title: 'Upload Documents',
      desc: 'Upload your driving licence, address proof, and identification documents.',
      icon: UploadCloud,
      accent: 'indigo'
    },
    {
      num: '5',
      title: 'Verification Process',
      desc: 'Our team reviews your application and verifies your documents.',
      icon: Clock,
      accent: 'indigo'
    },
    {
      num: '6',
      title: 'Application Approval',
      desc: 'Once approved, you will receive confirmation and insurance details.',
      icon: ShieldCheck,
      accent: 'indigo'
    },
    {
      num: '7',
      title: 'Pay Deposit',
      desc: 'Secure your vehicle by completing the required deposit payment.',
      icon: CreditCard,
      accent: 'indigo'
    },
    {
      num: '8',
      title: 'Drive Away',
      desc: 'Collect your vehicle and begin your rent-to-buy journey.',
      icon: Sparkles,
      accent: 'indigo'
    }
  ];

  const docs = [
    {
      title: 'Driving Licence',
      desc: 'Both sides of your valid photocard DVLA driving licence with relevant badges/underwriting details.',
      icon: UserCheck
    },
    {
      title: 'Proof of Address',
      desc: 'Two separate utility bills, bank statements or council tax summaries generated within the last 3 months.',
      icon: FileText
    },
    {
      title: 'Photo ID / Selfie Verification',
      desc: 'A quick, stateful biometric facial selfie confirmation of identity matching your photocards.',
      icon: Shield
    },
    {
      title: 'Income or Employment Information',
      desc: 'Consistent gig-partner earnings reports, PCO earnings invoices, or basic direct banking transaction history.',
      icon: TrendingUp
    }
  ];

  const eligibility = [
    'Minimum age requirement (Generally 21+ with verified record)',
    'Valid DVLA driving licence (No major serious endorsements)',
    'Proof of UK address (Consistent utilities or tenancy letters)',
    'Ability to meet payment requirements (Clean record and secure banking details)'
  ];

  const triggers = [
    {
      title: 'Fast Approval',
      desc: 'Decisions are generated by our underwriting team within days, getting you to step 8 quickly.',
      icon: ShieldCheck
    },
    {
      title: 'Flexible Payments',
      desc: 'Weekly contributions are automatically debited. Predictable and easy to track.',
      icon: CreditCard
    },
    {
      title: 'Trusted Process',
      desc: 'Clear legal parameters and complete transparency at every single step of your lease.',
      icon: Sparkles
    },
    {
      title: 'Dedicated Support',
      desc: 'Your designated concierge account rep handles all servicing, repairs, & questions instantly.',
      icon: PhoneCall
    }
  ];

  const faqs = [
    {
      q: 'How long does approval take?',
      a: 'Once steps 1 to 4 are completed (account created, profile saved, papers uploaded), our agent reviews and underwrites details within 24 to 48 hours.'
    },
    {
      q: 'What documents do I need?',
      a: 'We require a valid photocard driving licence, two current utility proof of address papers (within 90 days), and stable wage or direct debit profiles.'
    },
    {
      q: 'Can I apply online?',
      a: 'Yes! The entire application, from browse to upload to electronic underwriting signatures, is fully online.'
    },
    {
      q: 'When do I pay the deposit?',
      a: 'The deposit is paid after Stage 6 (Application Approval) to secure the selected vehicle in preparation for you to drive away.'
    }
  ];

  return (
    <div className="bg-gray-50/50 min-h-screen pb-16 font-sans antialiased" id="how-it-works-page">
      
      {/* 1. VIP Hero Section (500px height, luxury layout) */}
      <section 
        className="relative w-full h-[500px] bg-cover bg-center flex items-center px-4 sm:px-6 lg:px-8 overflow-hidden shadow-2xl animate-fade-in"
        style={{
          backgroundImage: `linear-gradient(90deg, rgba(8, 14, 28, 0.96) 0%, rgba(12, 22, 44, 0.72) 45%, rgba(15, 23, 42, 0.25) 100%), url('https://images.unsplash.com/photo-161843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1600')`
        }}
        id="how-works-hero-seq"
      >
        {/* Subtle grid pattern overlay */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:24px_24px] opacity-25 pointer-events-none z-0"></div>
        
        {/* Decorative graphic overlay */}
        <div className="absolute top-0 right-0 w-[45%] h-full bg-gradient-to-l from-black/20 to-transparent pointer-events-none z-0"></div>

        {/* Two-Column Grid layout: Left-Text layout & Right-Car layout */}
        <div className="w-full max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8 items-center relative z-10">
          
          {/* Left text block: Title, subtitle & custom badges with logo colors (#7CC242, #1F3F7A) */}
          <div className="lg:col-span-7 space-y-5 text-left">
            <div className="inline-flex items-center gap-1.5 bg-white/10 text-white text-[11px] font-black uppercase tracking-widest px-3.5 py-1.5 rounded-md border border-white/20">
              ⭐ Clear Path to Vehicle Ownership
            </div>
            
            <h1 className="font-sans font-black text-3xl sm:text-4xl lg:text-5xl text-white tracking-tight leading-none uppercase">
              How Our Rent-To-Buy <br />
              <span className="text-[#7CC242]">Process Works</span>
            </h1>
            
            <p className="text-gray-300 text-xs sm:text-sm md:text-base leading-relaxed max-w-xl font-normal">
              A simple step-by-step process to get behind the wheel of your next vehicle. Our simplified system bypasses heavy bank constraints.
            </p>
          </div>

          {/* Right Image element: stylish premium SUV */}
          <div className="hidden lg:flex lg:col-span-5 relative items-center justify-center select-none">
            <div className="w-full max-w-[400px] flex items-center justify-center relative">
              <img
                src="https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800"
                alt="R2BuyCar Modern Hybrid SUV Asset"
                className="w-full object-contain drop-shadow-[0_20px_40px_rgba(0,0,0,0.5)] transform -scale-x-100 lg:-mr-6 animate-fade-in"
              />
            </div>
          </div>

        </div>
      </section>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-16 space-y-24">

        {/* 2. Process Timeline (Main Section) */}
        <section className="space-y-12" id="process-timeline-main">
          <div className="text-center max-w-2xl mx-auto space-y-3">
            <span className="text-[10px] font-black text-indigo-600 uppercase tracking-widest block">The Journey Overview</span>
            <h2 className="text-3xl font-black text-slate-950 tracking-tight leading-none sm:text-4xl">
              Roadmap to Drive Away
            </h2>
            <p className="text-sm text-gray-500 font-sans leading-relaxed">
              We design simple steps focusing entirely on process clarity so you understand exactly what to expect.
            </p>
          </div>

          {/* Connected timeline steps - 8 connected steps layout */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 relative">
            
            {steps.map((st, i) => {
              const IconComponent = st.icon;
              return (
                <div 
                  key={i} 
                  className="group relative bg-white border border-gray-150 p-6 rounded-2xl flex flex-col justify-between space-y-6 hover:border-indigo-400 hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
                  id={`process-card-step-${st.num}`}
                >
                  {/* Backdrop Giant Number for premium modern look */}
                  <span className="absolute top-4 right-6 text-5xl font-sans font-black text-slate-100 group-hover:text-indigo-50 select-none transition-colors duration-300 leading-none">
                    0{st.num}
                  </span>

                  <div className="space-y-4">
                    {/* Icon frame code matching user branding perfectly */}
                    <div className="inline-flex p-3.5 bg-slate-50 text-slate-800 group-hover:bg-brand-secondary group-hover:text-brand-primary rounded-xl transition-all duration-300 shadow-xs">
                      <IconComponent className="w-5 h-5 stroke-[2]" />
                    </div>

                    <div className="space-y-1.5">
                      <h4 className="font-sans font-black text-sm text-slate-950 group-hover:text-indigo-600 transition-colors">
                        {st.title}
                      </h4>
                      <p className="text-[11px] text-gray-500 leading-relaxed font-sans font-light">
                        {st.desc}
                      </p>
                    </div>
                  </div>

                  {/* Connecting indicator bar bottom */}
                  <div className="w-8 h-1 bg-gray-100 group-hover:w-full group-hover:bg-indigo-600 rounded-full transition-all duration-300"></div>
                </div>
              );
            })}

          </div>
        </section>

        {/* 3. Documents Required Section */}
        <section className="bg-white rounded-3xl border border-gray-150 p-4 sm:p-12 shadow-sm space-y-10" id="documents-required-section">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="text-[10px] font-black text-indigo-600 uppercase tracking-widest block">Verification Checklist</span>
            <h2 className="text-3xl font-black text-slate-950 tracking-tight leading-none sm:text-4xl">
              Required Documents
            </h2>
            <p className="text-sm text-gray-500 font-sans leading-relaxed">
              To proceed through step 4 quickly, please prepare these standard verification items in digital or photograph format.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {docs.map((d, index) => {
              const DocIcon = d.icon;
              return (
                <div 
                  key={index} 
                  className="p-6 bg-slate-50/50 rounded-2xl border border-gray-150 hover:border-indigo-200 transition-all flex flex-col space-y-4"
                  id={`required-doc-box-${index}`}
                >
                  <div className="p-3.5 bg-indigo-50 text-indigo-600 rounded-xl self-start">
                    <DocIcon className="w-5 h-5" />
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-sans font-extrabold text-[#111A2E] text-sm">
                      {d.title}
                    </h4>
                    <p className="text-[11px] text-slate-500 font-sans leading-relaxed font-light">
                      {d.desc}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* 4. Eligibility Requirements */}
        <section className="bg-slate-950 text-white rounded-3xl p-4 sm:p-12 relative overflow-hidden shadow-xl border border-slate-850" id="eligibility-checklist-section">
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff05_1px,transparent_1px),linear-gradient(to_bottom,#ffffff05_1px,transparent_1px)] bg-[size:20px_20px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)]"></div>
          
          <div className="relative z-10 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            <div className="lg:col-span-5 space-y-4">
              <span className="text-[10px] font-black text-brand-primary uppercase tracking-widest">Pre-approval Parameters</span>
              <h3 className="font-sans font-black text-2xl sm:text-3xl tracking-tight leading-tight text-white mb-2">
                Eligibility Requirements Check
              </h3>
              <p className="text-xs text-slate-400 font-sans leading-relaxed font-light">
                Our simple underwriting metrics bypass standard high street credit reviews. Check if you meet the active criteria parameters shown here.
              </p>
            </div>

            <div className="lg:col-span-7 bg-white/5 border border-white/10 rounded-2xl p-4 sm:p-8 space-y-4.5">
              {eligibility.map((item, index) => (
                <div key={index} className="flex items-start gap-3">
                  <div className="p-1.5 bg-indigo-500/10 text-indigo-400 rounded-lg shrink-0 border border-indigo-500/25">
                    <Check className="w-3.5 h-3.5 stroke-[2.5]" />
                  </div>
                  <div className="space-y-0.5">
                    <p className="text-xs font-sans font-extrabold text-white leading-tight">
                      {item}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 5. Why Choose Us */}
        <section className="space-y-12" id="why-choose-us-grid">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="text-[10px] font-black text-indigo-600 uppercase tracking-widest block">Key Advantages</span>
            <h2 className="text-3xl font-black text-slate-950 tracking-tight leading-none sm:text-4xl">
              Why Choose Our Rent-to-Buy Process?
            </h2>
            <p className="text-sm text-gray-500 font-sans leading-relaxed">
              We focus purely on vehicle logistics availability and complete transparency rather than administrative delays.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {triggers.map((item, index) => {
              const CompIcon = item.icon;
              return (
                <div 
                  key={index}
                  className="p-6 bg-white border border-gray-150 rounded-2xl hover:border-indigo-400 group transition-all hover:shadow-lg flex flex-col space-y-4"
                >
                  <div className="p-3.5 bg-slate-50 text-slate-800 group-hover:bg-brand-secondary group-hover:text-brand-primary rounded-xl self-start transition-all duration-300">
                    <CompIcon className="w-5 h-5" />
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-sans font-black text-sm text-slate-950">
                      {item.title}
                    </h4>
                    <p className="text-[11px] text-slate-500 font-sans leading-relaxed font-light">
                      {item.desc}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* 6. Frequently Asked Questions */}
        <section className="bg-white rounded-3xl border border-gray-150 p-4 sm:p-10 shadow-sm space-y-8 animate-fade-in" id="timeline-faqs">
          <div className="text-center max-w-2xl mx-auto space-y-2">
            <span className="text-[10px] font-black text-indigo-600 uppercase tracking-widest block">Quick Answers</span>
            <h2 className="text-2xl sm:text-3xl font-black text-slate-950 tracking-tight">
              Process & Timeline FAQs
            </h2>
            <p className="text-xs sm:text-sm text-gray-500 font-sans">
              Frequently asked questions regarding processing latency, paperwork parameters, and deposit guidelines.
            </p>
          </div>

          <div className="max-w-3xl mx-auto divide-y divide-gray-105">
            {faqs.map((faq, fIdx) => (
              <div key={fIdx} className="py-4.5 font-sans">
                <button
                  onClick={() => setOpenFaqIdx(openFaqIdx === fIdx ? null : fIdx)}
                  className="w-full flex items-center justify-between text-left py-2 group focus:outline-none cursor-pointer"
                >
                  <h4 className="font-extrabold text-sm text-slate-950 group-hover:text-indigo-600 transition-colors">
                    {faq.q}
                  </h4>
                  {openFaqIdx === fIdx ? (
                    <ChevronUp className="w-4 h-4 text-slate-500 group-hover:text-indigo-600" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-slate-400 group-hover:text-indigo-600" />
                  )}
                </button>
                {openFaqIdx === fIdx && (
                  <div className="p-3 bg-slate-50 rounded-xl mt-2 text-xs text-slate-600 leading-relaxed font-light animate-fade-in">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* 7. Call To Action (Last section) */}
        <section className="bg-[#111A2E] text-white rounded-3xl p-4 sm:p-14 relative overflow-hidden text-center space-y-6" id="process-page-cta">
          {/* Subtle decoration matching visual look */}
          <div className="absolute inset-0 bg-brand-primary/5 [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_80%,transparent_100%)]"></div>
          
          <div className="relative z-10 space-y-3.5 max-w-xl mx-auto">
            <span className="text-[10px] font-black text-brand-primary uppercase tracking-widest bg-white/5 px-2.5 py-1.5 rounded-md border border-white/5 inline-block">
              Drive Towards Auto Ownership
            </span>
            <h2 className="text-3xl sm:text-4xl font-black tracking-tight text-white leading-none">
              Ready to Get Started?
            </h2>
            <p className="text-xs sm:text-sm text-slate-400 font-sans font-light">
              Submit your direct document checklist parameters or browse available active transport stocks below to secure instant leasing.
            </p>
          </div>

          <div className="relative z-10 flex flex-col sm:flex-row gap-4 items-center justify-center pt-2">
            <Link to="/cars" className="w-full sm:w-auto">
              <button className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-8 py-4 bg-brand-primary text-brand-secondary font-extrabold text-xs uppercase tracking-wider rounded-xl cursor-pointer hover:bg-brand-primary-hover active:scale-98 transition-all">
                Browse Cars
              </button>
            </Link>
            
            <Link to="/apply" className="w-full sm:w-auto">
              <button className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-8 py-4 bg-white/10 hover:bg-white/15 border border-white/15 text-white font-extrabold text-xs uppercase tracking-wider rounded-xl cursor-pointer active:scale-98 transition-all">
                Apply Now
                <ArrowRight className="w-4 h-4 text-brand-primary" />
              </button>
            </Link>
          </div>
        </section>

      </div>
    </div>
  );
}
